"""Add analytics tables

Revision ID: b19962794c53
Revises: 30628adc7197
Create Date: 2025-08-02 11:50:30.532128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID


# revision identifiers, used by Alembic.
revision: str = "b19962794c53"
down_revision: Union[str, Sequence[str], None] = "30628adc7197"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add analytics tables."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create analytics_events table
    op.create_table(
        "analytics_events",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("session_id", UUID(as_uuid=True), nullable=False),
        sa.Column("package_name", sa.String(), nullable=False),
        sa.Column("package_version", sa.String(), nullable=False),
        sa.Column("python_version", sa.String(), nullable=False),
        sa.Column("python_implementation", sa.String(), nullable=True),
        sa.Column("os_type", sa.String(), nullable=False),
        sa.Column("os_version", sa.String(), nullable=True),
        sa.Column("os_release", sa.String(), nullable=True),
        sa.Column("architecture", sa.String(), nullable=True),
        sa.Column("installation_method", sa.String(), nullable=True),
        sa.Column("virtual_env", sa.Boolean(), nullable=True),
        sa.Column("virtual_env_type", sa.String(), nullable=True),
        sa.Column("cpu_count", sa.Integer(), nullable=True),
        sa.Column("total_memory_gb", sa.Integer(), nullable=True),
        sa.Column("entry_point", sa.String(), nullable=True),
        sa.Column("extra_data", JSONB(), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes for analytics_events
    op.create_index(
        op.f("ix_analytics_events_id"), "analytics_events", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_events_api_key"),
        "analytics_events",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_session_id"),
        "analytics_events",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_package_name"),
        "analytics_events",
        ["package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_package_version"),
        "analytics_events",
        ["package_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_python_version"),
        "analytics_events",
        ["python_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_os_type"),
        "analytics_events",
        ["os_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_architecture"),
        "analytics_events",
        ["architecture"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_event_timestamp"),
        "analytics_events",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_processed"),
        "analytics_events",
        ["processed"],
        unique=False,
    )

    # Create composite indexes
    op.create_index(
        "idx_analytics_package_date",
        "analytics_events",
        ["package_name", "event_timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_analytics_api_key_date",
        "analytics_events",
        ["api_key", "event_timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_analytics_python_version",
        "analytics_events",
        ["package_name", "python_version"],
        unique=False,
    )
    op.create_index(
        "idx_analytics_os_type",
        "analytics_events",
        ["package_name", "os_type"],
        unique=False,
    )
    op.create_index(
        "idx_analytics_processing",
        "analytics_events",
        ["processed", "received_at"],
        unique=False,
    )
    op.create_index(
        "idx_analytics_aggregation",
        "analytics_events",
        ["package_name", "event_timestamp", "python_version", "os_type"],
        unique=False,
    )

    # Create daily_package_stats table
    op.create_table(
        "daily_package_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("package_name", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_events", sa.BigInteger(), nullable=False),
        sa.Column("unique_sessions", sa.BigInteger(), nullable=False),
        sa.Column("unique_users_estimate", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "package_name", "api_key", "date", name="uq_daily_package_stats"
        ),
    )
    op.create_index(
        op.f("ix_daily_package_stats_id"), "daily_package_stats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_package_stats_package_name"),
        "daily_package_stats",
        ["package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_package_stats_api_key"),
        "daily_package_stats",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_package_stats_date"),
        "daily_package_stats",
        ["date"],
        unique=False,
    )
    op.create_index(
        "idx_daily_stats_package_date",
        "daily_package_stats",
        ["package_name", "date"],
        unique=False,
    )
    op.create_index(
        "idx_daily_stats_api_key_date",
        "daily_package_stats",
        ["api_key", "date"],
        unique=False,
    )

    # Create other aggregate tables...
    op.create_table(
        "python_version_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("package_name", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("python_version", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("event_count", sa.BigInteger(), nullable=False),
        sa.Column("unique_sessions", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "package_name",
            "api_key",
            "python_version",
            "date",
            name="uq_python_version_stats",
        ),
    )
    op.create_index(
        op.f("ix_python_version_stats_id"), "python_version_stats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_python_version_stats_package_name"),
        "python_version_stats",
        ["package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_python_version_stats_api_key"),
        "python_version_stats",
        ["api_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_python_version_stats_python_version"),
        "python_version_stats",
        ["python_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_python_version_stats_date"),
        "python_version_stats",
        ["date"],
        unique=False,
    )
    op.create_index(
        "idx_python_stats_package_date",
        "python_version_stats",
        ["package_name", "date"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove analytics tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("python_version_stats")
    op.drop_table("daily_package_stats")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
