"""Add badge_tokens table

Revision ID: c9f6e8a2b5d1
Revises: a23e245e430c
Create Date: 2025-11-10 12:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9f6e8a2b5d1"
down_revision: Union[str, Sequence[str], None] = "a23e245e430c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add badge_tokens table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badge_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_badge_tokens_id"), "badge_tokens", ["id"], unique=False)
    op.create_index(
        op.f("ix_badge_tokens_token"), "badge_tokens", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove badge_tokens table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_badge_tokens_token"), table_name="badge_tokens")
    op.drop_index(op.f("ix_badge_tokens_id"), table_name="badge_tokens")
    op.drop_table("badge_tokens")
    # ### end Alembic commands ###
