"""Add subscription fields to user model

Revision ID: e19160229bb6
Revises: 9a1573a14fb8
Create Date: 2025-08-15 22:02:14.011522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e19160229bb6'
down_revision: Union[str, Sequence[str], None] = '9a1573a14fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add subscription fields to users table
    op.add_column('users', sa.Column('subscription_tier', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop subscription fields from users table
    op.drop_column('users', 'subscription_updated_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
