"""Remove geographic fields from analytics

Revision ID: e2420669e7ad
Revises: b19962794c53
Create Date: 2025-08-02 11:56:42.677591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2420669e7ad'
down_revision: Union[str, Sequence[str], None] = 'b19962794c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Remove geographic fields from analytics."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop geographic index first
    op.drop_index('idx_analytics_geographic', table_name='analytics_events')
    
    # Drop geographic columns
    op.drop_column('analytics_events', 'country_code')
    op.drop_column('analytics_events', 'timezone')
    
    # Drop geographic stats table if it exists
    op.drop_table('geographic_stats')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore geographic fields to analytics."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back geographic columns
    op.add_column('analytics_events', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('analytics_events', sa.Column('timezone', sa.String(), nullable=True))
    
    # Recreate geographic index
    op.create_index('idx_analytics_geographic', 'analytics_events', ['package_name', 'country_code', 'event_timestamp'], unique=False)
    op.create_index(op.f('ix_analytics_events_country_code'), 'analytics_events', ['country_code'], unique=False)
    
    # Recreate geographic stats table
    op.create_table('geographic_stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('package_name', sa.String(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('country_code', sa.String(length=2), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('event_count', sa.BigInteger(), nullable=False),
        sa.Column('unique_sessions', sa.BigInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('package_name', 'api_key', 'country_code', 'date', name='uq_geographic_stats')
    )
    op.create_index(op.f('ix_geographic_stats_id'), 'geographic_stats', ['id'], unique=False)
    op.create_index(op.f('ix_geographic_stats_package_name'), 'geographic_stats', ['package_name'], unique=False)
    op.create_index(op.f('ix_geographic_stats_api_key'), 'geographic_stats', ['api_key'], unique=False)
    op.create_index(op.f('ix_geographic_stats_country_code'), 'geographic_stats', ['country_code'], unique=False)
    op.create_index(op.f('ix_geographic_stats_date'), 'geographic_stats', ['date'], unique=False)
    op.create_index('idx_geo_stats_package_date', 'geographic_stats', ['package_name', 'date'], unique=False)
    
    # ### end Alembic commands ###
