"""add_is_admin_column_to_users

Revision ID: f0815de6fe96
Revises: e2420669e7ad
Create Date: 2025-08-02 20:59:53.916725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0815de6fe96'
down_revision: Union[str, Sequence[str], None] = 'e2420669e7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_signups_email'), table_name='email_signups')
    op.drop_index(op.f('ix_email_signups_id'), table_name='email_signups')
    op.drop_table('email_signups')
    op.alter_column('analytics_events', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # Add is_admin column with default False for existing users
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('analytics_events', 'extra_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('email_signups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('email_signups_pkey'))
    )
    op.create_index(op.f('ix_email_signups_id'), 'email_signups', ['id'], unique=False)
    op.create_index(op.f('ix_email_signups_email'), 'email_signups', ['email'], unique=True)
    # ### end Alembic commands ###
